### ISSUE TITLE
Cannot connect through ESPHome Bluetooth Proxy

### ISSUE THREAD

**Issue by filmkorn** [filmkorn/pyanova-nano#13]
If Home Assistant is using a BT Proxy, the device can be discovered but connection fails.

Errors (debug logging enabled on the Anova Nano integration).

- When establishing a connection:
```
2024-10-02 19:13:42.444 INFO (MainThread) [custom_components.anova_nano] Discovered: 58:93:D8:D8:7D:A4
2024-10-02 19:13:42.445 INFO (MainThread) [custom_components.anova_nano] Connecting to 58:93:D8:D8:7D:A4
2024-10-02 19:13:46.220 DEBUG (MainThread) [custom_components.anova_nano]
Traceback (most recent call last):
File "/usr/local/lib/python3.12/site-packages/pyanova_nano/client.py", line 367, in send_command
await data
asyncio.exceptions.CancelledError
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
File "/config/custom_components/anova_nano/coordinator.py", line 142, in _async_update_data
self.timer = await self.client.get_timer()
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.12/site-packages/pyanova_nano/client.py", line 525, in get_timer
timer = await self.send_read_command(ReadCommands.ReadTimer)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.12/site-packages/pyanova_nano/client.py", line 282, in send_read_command
return await self.send_command(command=command)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.12/site-packages/pyanova_nano/client.py", line 366, in send_command
async with asyncio.timeout(self._RX_DATA_TIMEOUT_SEC):
File "/usr/local/lib/python3.12/asyncio/timeouts.py", line 115, in __aexit__
raise TimeoutError from exc_val
TimeoutError
2024-10-02 19:13:46.223 DEBUG (MainThread) [custom_components.anova_nano] Finished fetching anova_nano data in 3.779 seconds (success: False)
```

```
2024-10-02 19:13:53.286 INFO (MainThread) [custom_components.anova_nano] Discovered: 58:93:D8:D8:7D:A4
2024-10-02 19:13:53.287 INFO (MainThread) [custom_components.anova_nano] Connecting to 58:93:D8:D8:7D:A4
2024-10-02 19:13:54.435 DEBUG (MainThread) [custom_components.anova_nano] Error ESP_GATT_CONN_FAIL_ESTABLISH while connecting: Connection failed to establish
Traceback (most recent call last):
File "/config/custom_components/anova_nano/coordinator.py", line 80, in _connect
await self._client.connect(
File "/usr/local/lib/python3.12/site-packages/pyanova_nano/client.py", line 140, in connect
await self._connect(self._device, timeout_seconds=timeout_seconds)
File "/usr/local/lib/python3.12/site-packages/pyanova_nano/client.py", line 171, in _connect
await self._client.connect()
File "/usr/local/lib/python3.12/site-packages/habluetooth/wrappers.py", line 311, in connect
connected = await super().connect(**kwargs)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.12/site-packages/bleak/__init__.py", line 615, in connect
return await self._backend.connect(**kwargs)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.12/site-packages/bleak_esphome/backend/client.py", line 77, in _async_wrap_bluetooth_operation
return await func(self, *args, **kwargs)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.12/site-packages/bleak_esphome/backend/client.py", line 327, in connect
await connected_future
bleak.exc.BleakError: Error ESP_GATT_CONN_FAIL_ESTABLISH while connecting: Connection failed to establish
```

- Updating the status
```
2024-10-02 19:14:12.745 INFO (MainThread) [custom_components.anova_nano] Connecting to 58:93:D8:D8:7D:A4
2024-10-02 19:14:16.963 DEBUG (MainThread) [custom_components.anova_nano]
Traceback (most recent call last):
File "/usr/local/lib/python3.12/site-packages/pyanova_nano/client.py", line 367, in send_command
await data
asyncio.exceptions.CancelledError
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
File "/config/custom_components/anova_nano/coordinator.py", line 142, in _async_update_data
self.timer = await self.client.get_timer()
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.12/site-packages/pyanova_nano/client.py", line 525, in get_timer
timer = await self.send_read_command(ReadCommands.ReadTimer)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.12/site-packages/pyanova_nano/client.py", line 282, in send_read_command
return await self.send_command(command=command)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.12/site-packages/pyanova_nano/client.py", line 366, in send_command
async with asyncio.timeout(self._RX_DATA_TIMEOUT_SEC):
File "/usr/local/lib/python3.12/asyncio/timeouts.py", line 115, in __aexit__
raise TimeoutError from exc_val
TimeoutError
2024-10-02 19:14:16.965 DEBUG (MainThread) [custom_components.anova_nano] Finished fetching anova_nano data in 4.220 seconds (success: False)
```

**Comment by filmkorn** [comment]
Resolved
